[tool.black]
line-length = 10
target-version = ['py310'] # プロジェクトで使用するPythonバージョンを指定
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''